[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "insider-trading"
version = "0.0.1"
authors = [
    { name="Aaron Kann" },
    { name="Ian Chang" },
    { name="Josh Tseng" },
    { name="Jonathan Grothe" },
]
description = "Data515 final project detecting insider trading on Polymarket"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.pylint]
disable = "C0301, C0301, R0904, R0912, R0914, R0915" 
# C0301: line length: some id strings need to be quite long
# C0301: invalid name: name follows polymarket naming conventions combined with pylint conventions
# R0904, R0912, R0914, R0915: 
# too many methods, branches, local vars, statements: 
# for our purposes it makes sense to overload it a bit for clean data collection and modularity

[project.urls]
Homepage = "https://github.com/changian8/insider-trading"
Issues = "https://github.com/changian8/insider-trading/issues"